export const FETCH_COLLECTION = 'FETCH_COLLECTION';
export const FETCH_COLLECTION_SUCCESS = 'FETCH_COLLECTION_SUCCESS';
export const FETCH_COLLECTION_FAILURE = 'FETCH_COLLECTION_FAILURE';

export const SHARE_CONTACT = 'SHARE_CONTACT';
export const SHARE_CONTACT_SUCCESS = 'SHARE_CONTACT_SUCCESS';
export const SHARE_CONTACT_FAILURE = 'SHARE_CONTACT_FAILURE';