export const FETCH_COLLECTION = 'FETCH_COLLECTION';
export const FETCH_COLLECTION_SUCCESS = 'FETCH_COLLECTION_SUCCESS';
export const FETCH_COLLECTION_FAILURE = 'FETCH_COLLECTION_FAILURE';

export const INTERACT = 'INTERACT';
export const INTERACT_SUCCESS = 'INTERACT_SUCCESS';
export const INTERACT_FAILURE = 'INTERACT_FAILURE';